### ISSUE TITLE
models.err showing non-existing path

### ISSUE THREAD

**Issue by LayZeeDK** [zpqrtbnk/Zbu.ModelsBuilder#113]
I received this error message today:

    Failed to build Live models.
    Property name "FeatureSlider" in type Content:"homePage" is used for properties with alias "featureSlider", "featureSlider". Names have to be unique. Consider using an attribute to assign different names to conflicting properties.
    
       at Umbraco.ModelsBuilder.Building.Builder.Prepare() in C:\Users\Stéphane\Documents\Development\Umbraco\Zbu\Zbu.ModelsBuilder\Umbraco.ModelsBuilder\Building\Builder.cs:line 164
       at Umbraco.ModelsBuilder.Umbraco.ModelsBuilderBackOfficeController.GenerateModels(String appData, String bin) in C:\Users\Stéphane\Documents\Development\Umbraco\Zbu\Zbu.ModelsBuilder\Umbraco.ModelsBuilder\Umbraco\ModelsBuilderBackOfficeController.cs:line 111
       at Umbraco.ModelsBuilder.Umbraco.LiveModelsProvider.GenerateModelsIfRequested(Object sender, EventArgs args) in C:\Users\Stéphane\Documents\Development\Umbraco\Zbu\Zbu.ModelsBuilder\Umbraco.ModelsBuilder\Umbraco\LiveModelsProvider.cs:line 83

The `C:\Users\Stéphane\Documents\Development(...)` part is not supposed to be there.

**Comment by zpqrtbnk** [comment]
Oops, indeed. What version is that?

**Comment by LayZeeDK** [comment]
I'm on Umbraco 7.4.3.

**Comment by LayZeeDK** [comment]
Have you tried this in recent versions?
