### ISSUE TITLE
Could not load type 'ModelBindingArgs' from assembly after update to 3.0.9

### ISSUE THREAD

**Issue by vascozorrinho** [zpqrtbnk/Zbu.ModelsBuilder#163]
Today i've updated my Umbraco ModelsBuilder and Umbraco ModelsBuilder Api to 3.0.9 and got this error.

```
[TypeLoadException]: Could not load type &#39;ModelBindingArgs&#39; from assembly &#39;umbraco, Version=1.0.6596.21111, Culture=neutral, PublicKeyToken=null&#39;.
   at Umbraco.ModelsBuilder.Umbraco.ModelsBuilderApplication.BindModelBindingException()
   at Umbraco.ModelsBuilder.Umbraco.ModelsBuilderApplication.ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   at Umbraco.Core.ApplicationEventHandler.OnApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   at Umbraco.Core.CoreBootManager.<Startup>b__37_0(IApplicationEventHandler x)
   at Umbraco.Core.EnumerableExtensions.ForEach[TItem](IEnumerable`1 items, Action`1 action)
   at Umbraco.Core.CoreBootManager.Startup(Action`1 afterStartup)
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
   at Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e)
[HttpException]: Could not load type &#39;ModelBindingArgs&#39; from assembly &#39;umbraco, Version=1.0.6596.21111, Culture=neutral, PublicKeyToken=null&#39;.
   at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app)
   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
[HttpException]: Could not load type &#39;ModelBindingArgs&#39; from assembly &#39;umbraco, Version=1.0.6596.21111, Culture=neutral, PublicKeyToken=null&#39;.
   at System.Web.HttpRuntime.FirstRequestInit(HttpContext context)
   at System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context)
   at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)
```

deleting bin folder didn't help. so i reverted to the previous version

**Comment by umbracoci** [comment]
What version of Umbraco are you running?

**Comment by vascozorrinho** [comment]
7.7.9

**Comment by zpqrtbnk** [comment]
well, that *should* work, but obviously it does not - investigating

**Comment by nul800sebastiaan** [comment]
@vascozorrinho  Is it possibe for you to zip up your bin folder and drop it here?

**Comment by nul800sebastiaan** [comment]
@vascozorrinho Never mind, we found it! Fixing now.

**Comment by zpqrtbnk** [comment]
New version 3.0.10 has been uploaded to NuGet and is being indexed now.

Sorry about it!

**Comment by vascozorrinho** [comment]
thanks guys!
