### ISSUE TITLE
Error when running custom ver. 2.0.3.34.

### ISSUE THREAD

**Issue by alremus** [zpqrtbnk/Zbu.ModelsBuilder#30]
I download Hybrid Framework for Umbraco v7 Clean from https://github.com/jbreuer/Hybrid-Framework-for-Umbraco-v7-Clean.
In Umbraco.Site and Umbraco.Extensions projects in solution I update Zbu.ModelsBuilder and Zbu.ModelsBuilder.AspNet to version 2.0.3-final. 
Then I install ZpqrtBnk Umbraco ModelsBuilder ver. 2.0.3.34.
When I run tool in Visual Studio 2012 or 2013 I got output:

ZbuModelsBuilder: Starting 2015-01-13 23:25:02.
ZbuModelsBuilder: ZbuModelsBuilder failed to generate code: AggregateException: One or more errors occurred.
ZbuModelsBuilder:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Zbu.ModelsBuilder.AspNet.ModelsBuilderApi.ValidateClientVersion()
   at Zbu.ModelsBuilder.CustomTool.CustomTool.ZbuModelsBuilder.GenerateRaw(String wszInputFilePath, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, String& errMsg)
ZbuModelsBuilder: Inner: JsonSerializationException: Error getting value from 'ZERO_CHAR_VALUE' on 'System.Version'.
ZbuModelsBuilder:    at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value)
   at System.Net.Http.Formatting.JsonMediaTypeFormatter.<>c__DisplayClassd.<WriteToStreamAsync>b__c()
   at System.Threading.Tasks.TaskHelpers.RunSynchronously(Action action, CancellationToken token)
ZbuModelsBuilder: Inner: NotSupportedException: Specified method is not supported.
ZbuModelsBuilder:    at System.Reflection.MdFieldInfo.get_FieldHandle()
   at System.Reflection.Emit.DynamicILGenerator.GetTokenFor(RuntimeFieldInfo runtimeField, RuntimeType rtType)
   at System.Reflection.Emit.DynamicILGenerator.Emit(OpCode opcode, FieldInfo field)
   at Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateGetFieldIL(FieldInfo fieldInfo, ILGenerator generator)
   at Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateGet[T](FieldInfo fieldInfo)
   at Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateGet[T](MemberInfo memberInfo)
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
ZbuModelsBuilder: AggregateInner: JsonSerializationException: Error getting value from 'ZERO_CHAR_VALUE' on 'System.Version'.
ZbuModelsBuilder:    at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value)
   at System.Net.Http.Formatting.JsonMediaTypeFormatter.<>c__DisplayClassd.<WriteToStreamAsync>b__c()
   at System.Threading.Tasks.TaskHelpers.RunSynchronously(Action action, CancellationToken token)

**Comment by zpqrtbnk** [comment]
Looking into it.

**Comment by zpqrtbnk** [comment]
Exception takes place in the VSIX extension before even reaching the website, and is really strange (Json.Net failing to build the dynamic serialization code...) - thinking about a possible issue with the extension: can you make sure you call all running instances of Visual Studio, then re-open and try again?

**Comment by alremus** [comment]
You mean close all running instances of Visual Studio? It doesn't helps. 
I try on other umbraco project and the some message appear.

**Comment by zpqrtbnk** [comment]
Yes that's what I meant. Sorry to head it doesn't help.
Will look further into it... looks quite strange.

**Comment by zpqrtbnk** [comment]
Another issue with serializing System.Version - going to replace it with strings in 2.0.4.

**Comment by alremus** [comment]
This solved the problem.
I needed to update package Microsoft.CodeAnalysis.Common.
Now everything works fine.
