### ISSUE TITLE
Custom base class not working

### ISSUE THREAD

**Issue by jbreuer** [zpqrtbnk/Zbu.ModelsBuilder#41]
When you have a partial class and you want to give that partial class it's own base class it's currently not supported. 

For example:

Generated class:
public partial class ProductDetails : Base, IHeader

Custom partial class:
public partial class ProductDetails : HeaderCompostion

HeaderCompostion class (only here for clarification)
public class HeaderCompostion : Base, IHeader

So in this case it would be nice if the generated class wouldn't have the base class because that's already defined in the partial class.

Currently getting this error when I try the above:
ZbuModelsBuilder: ZbuModelsBuilder failed to generate code: Exception: Response status code does not indicate success (InternalServerError)
{"Message":"An error has occurred.","ExceptionMessage":"Type alias \"ProductDetails\" has a more than one parent class.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at Zbu.ModelsBuilder.Building.Builder.Prepare()\r\n   at Zbu.ModelsBuilder.Building.Builder..ctor(IList`1 typeModels, ParseResult parseResult, String modelsNamespace)\r\n   at Zbu.ModelsBuilder.AspNet.ModelsBuilderApiController.GetModels(GetModelsData data)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.<GetExecutor>b__c(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)"}
ZbuModelsBuilder:    at Zbu.ModelsBuilder.AspNet.ModelsBuilderApi.EnsureSuccess(HttpResponseMessage result)
   at Zbu.ModelsBuilder.AspNet.ModelsBuilderApi.GetModels(Dictionary`2 ourFiles, String modelsNamespace)
   at Zbu.ModelsBuilder.CustomTool.CustomTool.ZbuModelsBuilder.GenerateRaw(String wszInputFilePath, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, String& errMsg)

**Comment by jbreuer** [comment]
Skype chat to clarify why I would like to do this:

[02-03-15 16:28:07] Jeroen Breuer - Developer: Hi
[02-03-15 16:28:33] Jeroen Breuer - Developer: Can I ask a question about the Models Builder and Compositions?
[02-03-15 16:29:22] Stéphane Gay: hey
[02-03-15 16:29:23] Stéphane Gay: sure
[02-03-15 16:30:19] Jeroen Breuer - Developer: With a doctype that has compositions is generated as a class with interfaces for each composition
[02-03-15 16:30:44] Jeroen Breuer - Developer: What if there is a property on a composition that I want to override?
[02-03-15 16:31:22] Jeroen Breuer - Developer: I know you can do that with the ImplementPropertyType attribute on a partial class
[02-03-15 16:31:36] Stéphane Gay: properties that come from compositions are defined on the interface BUT are actually implemented in each content type
[02-03-15 16:31:57] Jeroen Breuer - Developer: But would that mean I have to do it on each generated models that inherits that interface?
[02-03-15 16:32:05] Stéphane Gay: if you want to override one of these properties... you have to either do it on each generated models...
[02-03-15 16:32:21] Stéphane Gay: or to do it on a base class that all of these models would inherit
[02-03-15 16:32:58] Jeroen Breuer - Developer: the base class sounds interesting
[02-03-15 16:33:15] Jeroen Breuer - Developer: the models all have a base class, but that's the base doctype
[02-03-15 16:33:16] Stéphane Gay: that's the only way I see (and I think I've used it)
[02-03-15 16:33:38] Jeroen Breuer - Developer: I don't know if the base doctype has those properties
[02-03-15 16:33:44] Stéphane Gay: well... you need to insert an intermediate class between that base doctype and your models
[02-03-15 16:33:57] Jeroen Breuer - Developer: is that possible?
[02-03-15 16:34:02] Stéphane Gay: eg ContentBase -> Composition -> Model
[02-03-15 16:34:07] Stéphane Gay: should be possible
[02-03-15 16:34:30] Stéphane Gay: create your Composition class that inherits from ContentBase (and implements the IComposition interface)
[02-03-15 16:34:43] Stéphane Gay: then for each model, create a partial & specify that the model interits from Composition
[02-03-15 16:34:50] Stéphane Gay: should work
[02-03-15 16:35:07] Stéphane Gay: (thinking it might be good to put that in the doc once you get it to work)
[02-03-15 16:35:19] Jeroen Breuer - Developer: Won't that give errors with the generated classes
[02-03-15 16:35:24] Jeroen Breuer - Developer: those also have a base class
[02-03-15 16:35:38] Jeroen Breuer - Developer: can you tell your partial class to have a different base class?
[02-03-15 16:36:13] Stéphane Gay: I guess that at the moment they have base class ContentBase... if you specify _another_ inheritance in your partial, I think we detect that and when you rebuild, we do _not_ set a base class on the models
[02-03-15 16:36:21] Stéphane Gay: at least that's the plan ;)
[02-03-15 16:36:30] Stéphane Gay: I'll feel better when you tell me it works
[02-03-15 16:36:56] Jeroen Breuer - Developer: Haha thanks I'll do some testing this week
[02-03-15 16:37:21] Stéphane Gay: plz let me know how it goes (email me code if you can) => must put it in the docs, it's good material
[02-03-15 16:37:38] Jeroen Breuer - Developer: Sure I will

**Comment by zpqrtbnk** [comment]
So the plan was to have it work OOTB. And I'm pretty sure that if your content type is a root content type and would inherit from PublishedContentModel, we do detect that it already has a base class. But I may be wrong. In your case, your content type is not a root content, it has a parent content type... and I probably overlooked that situation.

Will fix.

**Comment by zpqrtbnk** [comment]
Reproduced. If a type does not have a parent, its generated model should inherit from PublishedContentModel - unless we have a partial that defines another inheritance. That works. However it fails if the type does have a parent. Fixing.

**Comment by zpqrtbnk** [comment]
Fixed - but we cannot ensure that the inheritance chain is not broken. If type TypeA has parent TypeB and you create a partial class for TypeA indicating that it inherits from Whatever... then it's up to you to make sure that Whatever somehow inherits from TypeB. You're on your own ;-)

**Comment by jbreuer** [comment]
No problem :-). I just want an extra base class that has the correct parent in the chain. That way I can create my composition interfaces on that.
