### ISSUE TITLE
There are multiple root elements

### ISSUE THREAD

**Issue by calaa** [zpqrtbnk/Zbu.ModelsBuilder#55]
Updated today (CT 2.1.3.43, NuGet: 2.1.3-beta001).

Getting following error:

ZbuModelsBuilder: Starting v2.1.3.43 16.06.2015 17:13:09.
ZbuModelsBuilder: ZbuModelsBuilder failed to generate code: XmlException: There are multiple root elements. Line 3, position 2.
ZbuModelsBuilder:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at Zbu.ModelsBuilder.CustomTool.VisualStudio.VisualStudioHelper.ToHierarchy(Project project)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Zbu.ModelsBuilder.CustomTool.VisualStudio.VisualStudioHelper.GetSourceItem(String inputFilePath)
   at Zbu.ModelsBuilder.CustomTool.CustomTool.ZbuModelsBuilder.GenerateRaw(String wszInputFilePath, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, String& errMsg)

**Comment by zpqrtbnk** [comment]
We are definitively seeing some issues with some type of projects/solutions. Is there any chance you could ZIP and share your project w/me (email stephane@umbraco.com)? Would remain private of course, but would greatly help debugging, else I'd need to send you temp DLLs etc.

**Comment by calaa** [comment]
Thank for prompt reply.The problem is that the ZIP is about 500mb. Are there any other ways?

**Comment by zpqrtbnk** [comment]
wow - the ZIP is 500mb? talk about a huge project! OK, unless you have stuff in there such as medias, images, etc that you can remove to reduce the size of the zip... Can you just ZIP and send only those files: the main .sln file, and every project file (eg .csproj) it references?

**Comment by calaa** [comment]
Images and other stuff are already removed.... but I'll try to remove as much as possible (that the project is startable and that the error still occurs). Give me some minutes ;-).

**Comment by calaa** [comment]
Strange... moved the whole project to desktop (to do the ZIP-stuff)
Removed all Websites (not Web Applications) and the NSPROJ-Project (Node JS) and it works.
(The folder of the project is still there just removed it from the solution)

Tried to remove project by project but it just works when all of them are removed.

**Comment by zpqrtbnk** [comment]
That makes sense: one of the project is causing the issue. So you do NOT want to remove any project, including the node one. Just the extra images and stuff. Then, you can WeTransfer or DropBox it.

**Comment by zpqrtbnk** [comment]
Have been able to reproduce the issue. Fixed, will release an update soon.

**Comment by zpqrtbnk** [comment]
beta008 is now out, would be great if you could test it

**Comment by calaa** [comment]
YES!
IT WORKS!

Thank you for the super fast fix ;-).
